### PR TITLE
Add "pause" menu

### LINKED ISSUE #585: Pause menu (that doesn't pause the game) accessible from shooting rounds (at least)

### LINKED ISSUE #586: Option to exit to main menu from a match

### PR DESCRIPTION
**Pull request by toberge**
image

Barely solves #138 
Closes #586 
Closes #585

### CODE REVIEW

**Review by Fueredoriku — CHANGES_REQUESTED** [review]
Good feature! 😁👍
I have some feedback and one requested change:

Feedback:
- I think we should rename the "Not paused" title to just "Menu" or "Pause Menu"
- The keybind for the gamepadaction of opening the menu should probably be mapped to the right button and not the left. Whic would be "start[gamepad]" instead of "exit[gamepad]". Alternatively it could be both.

Requested change:
- Currently the pause menu breaks zooming. If zooming is performed and the player then pauses and continues the game, zooming will remain broken until player is respawned.

**Comment by toberge** [comment]
Fixened

**Review by Fueredoriku — CHANGES_REQUESTED** [review]
Some feedback:
- It seems you can't select between buttons with a gamepad
- Opening more than one menu will deselect all buttons for all players except the newest menu

And a bit more nickpicky:
- For gamepads specifically: When zoomed, if you open a menu, the hand will remain in zoomed position until you zoom in and out again (I suspect this is due to gamepads having toggle behaviour for zooming that is not accounted for) 
image

**Comment by toberge** [comment]
Setting this as draft again since it's waaaay more work than I assumed 🙃

**Comment by toberge** [comment]
Redone in #759

**Pull request closed without merging**
